version: '3'

services:
  annotatechange:
    image: datannotationplatform
    build: .
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.annotatechange.rule=Host(`perfchangeannotator.com`)"
      - "traefik.http.routers.annotatechange.entrypoints=websecure"
      - "traefik.http.routers.annotatechange.tls=true"
      - "traefik.http.routers.annotatechange.tls.certresolver=le"
      - "traefik.http.services.annotatechange.loadbalancer.server.port=7831"
    networks:
      - internal
      - web
    ports:
      - "80:7831"
    depends_on:
      - db
    volumes:
      - ./persist/instance:/home/annotatechange/instance

  db:
    image: mysql
    env_file: .env
    user: "root:root"
    volumes:
      - ./persist/mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=realiselab@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
